version: "3"
services:
  web:
    image: nginx:1.25.1
    ports:
      - 80:80
    networks:
      - deming
    volumes:
      - $PWD/deming.conf:/etc/nginx/conf.d/default.conf
  deming:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    networks:
      - deming
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_PERSISTENT_PATH}:/var/lib/mysql 
    ports:
      - "3306"
    networks:
      - deming
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 3s
        timeout: 60s
        retries: 5

networks:
  deming:
